language: java

addons:
  apt:
    packages:
      - awscli

services:
  - docker

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn package -B -P kafka-2.0.0
  - docker build -t secor:0.29 .

deploy:
  provider: script
  script: bash ci/ecr_push
  on:
    branch: master
  edge: true
