#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

docker run --rm -it -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 723255503624.dkr.ecr.us-east-1.amazonaws.com
docker tag secor:0.29 723255503624.dkr.ecr.us-east-1.amazonaws.com/secor:0.29
docker push 723255503624.dkr.ecr.us-east-1.amazonaws.com/secor:0.29
